version: 0.0
os: linux
files:
  - source: bin/
    destination: /opt/MyApps/Utils/bin/

  - source: libs/   
    destination: /opt/MyApps/Utils/libs/

  - source: templates/
    destination: /opt/MyApps/Utils/templates/

  - source: README.md
    destination: /opt/MyApps/Utils/

hooks:
  AfterInstall:
    - location: scripts/MakeExecutable.sh
      timeout: 300
      runas: root
