version: 0.0
os: linux
files:
  - source: bin/
    destination: /opt/MyApps/UtilsApp/bin/

  - source: libs/   
    destination: /opt/MyApps/UtilsApp/libs/

  - source: README.md
    destination: /opt/MyApps/UtilsApp/

  - source: autocompletes/
    destination: /opt/MyApps/UtilsApp/autocompletes

hooks:
  AfterInstall:
    - location: scripts/MakeExecutable.sh
      timeout: 300
      runas: root
