# Copy source macro

macro(copySrc src dest exec)
    make_directory(${dest})
    file(GLOB files RELATIVE ${src} ${src}/*)
    foreach(file ${files})
        set(fullpathsrc "${src}/${file}")
        set(fullpathdest "${dest}/${file}")
        if(IS_DIRECTORY ${fullpathsrc})
            copySrc(${fullpathsrc} ${fullpathdest} exec)
        else(IS_DIRECTORY ${fullpathsrc})
            message("    [INFO] Copying: ${file} from ${src} to ${dest}")
            if(exec)
                file(COPY ${fullpathsrc} DESTINATION ${dest}
                    FILE_PERMISSIONS WORLD_EXEC)
            else(exec)
                file(COPY ${fullpathsrc} DESTINATION ${dest})
            endif(exec)
            file(COPY ${fullpathsrc} DESTINATION ${dest})
        endif(IS_DIRECTORY ${fullpathsrc})
    endforeach(file)
endmacro(copySrc)

set(SRC "${CMAKE_ARGV3}")
set(DEST "${CMAKE_ARGV4}")
set(MODEZ "${CMAKE_ARGV5}")

if (${MODEZ} STREQUAL "EXEC")
    message(STATUS "[INFO][EXEC] Recursively copying contents of directory ${SRC} to ${DEST} and making them executable")
    copySrc(${SRC} ${DEST} TRUE)
else(${MODEZ} STREQUAL "EXEC")
    message(STATUS "[INFO][NOEXEC] Recursively copying contents of directory ${SRC} to ${DEST} and not changing permissions")
    copySrc(${SRC} ${DEST} FALSE)
endif(${MODEZ} STREQUAL "EXEC")
#avoidDir(${SRC} ${DEST})