#!/usr/bin/env python

import datetime
import os
import glob
import time
import re
import gzip
import socket

class SlGrep:
    #Return date from string
	@staticmethod
	def getDate(datestr):
		t = None
		if len(datestr.split("-")) == 1:
			t = time.gmtime(float(datestr))
		else:
			try:
				t = time.strptime(datestr, "%Y-%m-%d-%H-%M")
			except:
				print("Could not convert date: " + datestr + ". Needs to be %Y-%m-%d-%H-%M")
				sys.exit(1)
		tstamp = time.mktime(t)
		return datetime.datetime.fromtimestamp(tstamp)
	
	# Compute files to check
	@staticmethod
	def fileLogic(root, start = None, end = None):
		filelist = glob.glob(root + "/service_log.*")
                filelist.extend(glob.glob(root + "/service_log.*.gz"))
		filelist.extend(glob.glob(root + "/transmitted/service_log.*.gz"))
		retval = []

		if start == None:
			givenstart = datetime.datetime.now() - datetime.timedelta(hours = 48)
		else:
			givenstart = SlGrep.getDate(start) - datetime.timedelta(hours = 1)
		if end == None:
			givenend = datetime.datetime.now()
		else:
			givenend = SlGrep.getDate(end)
		
		for f in filelist:
			fdate = SlGrep.getDate(f.split(".")[1] + "-00")
			if not (fdate < givenstart or fdate > givenend):
				retval.append(f)
		return retval

	# Main Grep function
	@staticmethod
	def grep(filename, strlist = [], start = None, end = None):
		if filename.endswith(".gz"):
			fp = gzip.open(filename, "r")
		else:
			fp = open(filename, "r")
		logs = fp.read().split("EOE")
                print("Queries in: " + socket.gethostname() + ":" + filename + " : " + str(len(logs)))
                count = 0
		for query in logs:
                        count = count + 1
			logic = True
			for pattern in strlist:
				if logic and (not re.search(pattern, query, re.MULTILINE)):
					logic = logic and False
			if logic and end != None:
				sObj = re.search("EndTime=(.*)", query, re.MULTILINE)
				if sObj:
					qetime = datetime.datetime.fromtimestamp(time.mktime(time.strptime(sObj.group(1), "%a, %d %b %Y  %H:%M:%S %Z")))
					if qetime < SlGrep.getDate(end) and qetime >= SlGrep.getDate(start):
						logic = True
                                        else:
                                                logic = False
			if logic:
				print(query)
				print("\n")
                print("Count = " + str(count))

			

		
def main():
	root = "/apollo/env/SERVICE_P/var/output/logs"
	patterns = "QUERY_P".split(",")
	start = "START_P"
	end = "END_P"
	if start == "None":
		start = None
	if end == "None":
		end = None
	filelist = SlGrep.fileLogic(root, start, end)
	for f in filelist:
		print("\n\nInspecting file: " + socket.gethostname() + ":" + f)
		SlGrep.grep(f, patterns, start,end)

if __name__ == "__main__":
	main()
